import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/common/ThemeProvider";
import { Navbar } from "@/components/common/Navbar";
import FlyingDragon from "@/components/common/FlyingDragon";
import ReactLenis from "lenis/react";
import Footer from "@/components/common/Footer";

const hankenGrotesk = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hanken-grotesk",
});

export const metadata: Metadata = {
  title: "Portofolio Vaka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${hankenGrotesk.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <ReactLenis root>
            <Navbar />
            {children}
            <FlyingDragon /> {/* ✅ Tambahin ini */}
            <Footer />
          </ReactLenis>
        </ThemeProvider>
      </body>
    </html>
  );
}
